const captions = {
    "Jeans": [
        "Denim days and coffee vibes ☕👖",
        "Classic never goes out of style 💙",
        "Feeling comfy in my jeans life 🔥",
        "Jeans,the uitimate wardrobe staple",
        "Denim love",
        "it's blue jean kind a dream",
        "Feelin'blue",
        "This outfit is jeanius, am i right?",
        "Huge fan of flared jeans.",
        "Jeans are not just a piece of clothing, they are a lifestyle.",
        "Denim dreams and coffee beans ☕👖",
        "Blue jeans, white tee, and a whole lot of confidence.",
        "Denim on denim, because why not?",
        "Jeans: the perfect blend of comfort and style.",
        "Flared jeans are back, and I’m here for it!",
        "Denim vibes and good times.",
        "Jeans: the ultimate wardrobe staple.",
        "Feeling blue never looked so good.",
        "Denim days are the best days.",
        "Jeans: because sometimes you just need to feel comfy and stylish.",
        "Denim is always a good idea.",
        "Flared jeans are my happy place.",
        "Denim love affair.",
        "Jeans: the perfect canvas for any outfit.",
        "Denim dreams come true.",
        "Blue jeans, big dreams.",
        "Denim is my second skin.",
    ],
    "Choli": [
        "Lost in the swirl of my favorite lehnga",
        "Lehanga vibes and good times only",
        "lehanga on point,vibes on fleek",
        "Sparkle and shine in a Lehanga divine",
        "Lehanga magic in full swing",
        "Lehanga vibes, radiating grace",
        "Lehanga moments, cherished and bright",
        "Cover me in sunshine",
        "Make them stop&stare",
        "Look at her now",
        "Let your be your crown",
        "Desi masterpiece lehnga",
        "she's got the lehanga twrill",
        "Desi vibes are on point",
        "My Lehanga is a piece of cultural heritage",
        "Festivals call for lehanga and happy vibes",
        "My lehanga's so extra, it twirls by itself!",
        "in a black lehanga, teadition meets trend",
        "Swarg se utri hui kokil kanthi apsara lg rahi ho",
        "Wanna sing chura liya hai tumhe jo dil ko but no one is stealing",
        "Why slay when you can Dhoom machale"
    ],
    "Top": [
        "Just a cute top and a vibe 🎀",
        "Top of the world, top in style!",
        "Simple, soft, and stylish 🌸",
        "Tops that make you feel like a queen 👑",
        "Casual chic with a touch of elegance ✨",
        "Tops that speak louder than words 💬",
        "Feeling fabulous in my favorite top 💖",
        "When in doubt, wear a cute top 💁‍♀️",
        "Tops that make every outfit pop! 💥",
        "Soft fabrics, bold styles 🌟"
    ],
    "Kurti": [
        "kurti game strong",
        "kurti vibes and good times only",
        "kurti on point,vibes on fleek",
        "Sparkle and shine in a kurti divine",
        "kurti magic in full swing",
        "kurti vibes, radiating grace",
        "Embrace your culture, rock that kurti!",
        "Kurti love, desi vibes",
        "Nothing beats a comfort and style kurti",
        "Shorts and skin All is cool but kurti with jhumka or bindi uff",
        "Kurti: the perfect blend of tradition and trend",
        "Kurti love, desi vibes",
        "Kurti: the perfect blend of tradition and trend",
        "Alexa play 'silky kurti ae'",
        "Being sanskari with the combination of denim jeans with traditional kurti",
    ],
    "Anniversary": [
        "Years passed, love lasts 💖",
        "Together is a beautiful place to be ❤",
        "One more year of magic ✨",
        "Celebrating love, laughter, and happily ever after 💍",
        "Anniversary vibes: love in the air 💕",
        "Cheers to us and our forever 🥂",
        "Another year of love, laughter, and adventures together 🌟",
        "Anniversary bliss: just you and me 💞",
        "Forever looks good on us 💑",
        "Happy anniversary to my partner in crime 💘",
        "Anniversary love: stronger than ever 💪",
        "Celebrating our love story, one year at a time 📖",
        "Happy anniversary to the one who makes my heart smile 😊",
        "Anniversary magic: love that never fades ✨",
        "Cheers to the love that keeps growing stronger every year 🥳",
        "Anniversary love: a journey of a lifetime 🚀",
        "Happy anniversary to the one who completes me 💖",
        "Celebrating our love, today and always 💞",
        "Anniversary vibes: love that never goes out of style 💕",
        "Another year of love, laughter, and adventures together 🌟",
        "Happy anniversary to my forever love 💘",
        "Happy Anniversary, Honey! You Make Me The Happist Man in The World",
        "You mean a lot to me. i am alive because i am living with you and within you.",
        "Been about you since i met you. #Happy_anniversary",
        "if truth is beauty, how come no one has their hair done in library?",
        "Wishing you a lot of happiness today and forever more",
        "Happy Anniversary to the person i want beside me every night for the rest of forever.",
        "The risk i took was calculated ,but man, i am bad at math.",
        "For the two of us,home isn't a place.it is a person.And we are finally home.",
        "I love you because i live in you.",
        "Loved you yesterday, love you still, always have, always will.",
        "Always in my mind, forever in my heart-Happy anniversary!",
        "I never feel more i'm trying to put sunscreen on my back.",
        "Go to heaven for the climate, hell for the company.",
        "You are absolutely beatiful both inside and out,happy anniversary to my gorgeous wife.",
        "I loved you then, i love still, always have, always will.",
        "A wedding anniversary is the celebration of love, partnership, toerance and tenactiy, the order varies for any given year",
        "in you, i've found the love of my life and my closest, truest friend."
    ],
    "Best Friend": [
        "Partners in crime 👯‍♀",
        "Best friends make life 100x better 💜",
        "No drama, just BFF vibes 💫",
        "Besties for life, no matter the distance 🌍",
        "Friendship goals: always there for each other 🤝",
        "Laughing together is the best therapy 😂",
        "Best friends: the family we choose 💖",
        "Together we can conquer the world 🌎",
        "Friendship is a treasure that never fades 💎",
        "Making memories with my favorite person 📸",
        "Best friends: the perfect blend of fun and support 🎉",
        "Through thick and thin, we’ve got each other’s backs 💪",
        "Besties who slay together, stay together 👑",
        "Friendship is the glue that holds us together 👫",
        "Best friends: the ones who know all your secrets 🤫",
    ],
    "Attitude": [
        "I’m not special, I’m just limited edition 😎",
        "Take me as I am or watch me as I go 🚶",
        "I don’t follow others, I make my own path 💥",
        "Confidence is my best accessory 💁‍♀️",
        "Attitude is everything, so pick a good one 💪",
        "I’m not bossy, I just know what you should be doing 😏",
        "I’m not here to fit in, I’m here to stand out 🌟",
        "My attitude is a reflection of my personality 💯",
        "I’m not perfect, but my attitude is on point 🔥",
        "I don’t do drama, I do vibes ✌️"
    ],
    "Wedding": [
        "Shaadi vibes activated 💍",
        "All glammed up for the big day ✨",
        "Here for the food and fun 😋",
        "Wedding bells and love spells 💖",
        "Dancing the night away at this wedding 💃",
        "Love is in the air, and so is the wedding cake 🍰",
        "Celebrating love, laughter, and happily ever after 🥂",
        "Wedding vibes: love, joy, and a little bit of chaos 🎉",
        "Cheers to the newlyweds! 🥳",
        "Wedding magic: where dreams come true ✨"
    ]
};

function showCaptions(category) {
    const captionBox = document.getElementById('captionBox');
    const captionTitle = document.getElementById('captionTitle');
    const captionList = document.getElementById('captionList');

    captionTitle.innerText = category + " Captions";
    captionList.innerHTML = "";

    captions[category].forEach(caption => {
        const li = document.createElement("li");
        li.innerText = caption;
        captionList.appendChild(li);
    });

    captionBox.style.display = "block";
}